- name: Load all docker images on each node
  hosts: all
  tags: copy
  tasks:
    - name: Copy images to target servers
      copy: src=data/images.tgz dest=/tmp/images.tgz
    - name: Extract images to local docker instance
      shell: docker load < /tmp/images.tgz 

- name: Run Containers
  hosts: all
  tasks:
    - name: Run Hello World
      docker:
        name: "hello-devcon"
        docker_api_version: "1.18"
        image: "devcon/hello:1.0"
        state: "reloaded"
        expose:
          - "8000"
        ports:
          - "8000:8000"
        restart_policy: "always"

- name: Install load balancer on one node
  hosts: all[0]
  tasks:
    - name: Generate Nginx Config
      template: src=nginx.conf.j2 dest=/tmp/devcon-nginx.conf
    - name: Run Load Balancer
      docker:
        name: "nginx"
        docker_api_version: "1.18"
        image: "nginx:1.9.15"
        state: "reloaded"
        expose:
          - "8080"
        ports:
          - "8080:8080"
        volumes:
          - /tmp/devcon-nginx.conf:/etc/nginx/conf.d/default.conf
        restart_policy: "always"
